[workspace]
resolver = "2"

members = ["q*"]

[workspace.dependencies]
nom = "7.1.3"
nom_locate = "4.2.0"
indicatif = "0.17.7"
rayon = "1.8.0"
itertools = "0.13.0"
num-integer = "0.1.44"
glam = "0.29.2"
